// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/pb/pb_example_gogo.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PbExampleGogo struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbExampleGogo) Reset()         { *m = PbExampleGogo{} }
func (m *PbExampleGogo) String() string { return proto.CompactTextString(m) }
func (*PbExampleGogo) ProtoMessage()    {}
func (*PbExampleGogo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df87a36eeb4579b, []int{0}
}
func (m *PbExampleGogo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbExampleGogo.Unmarshal(m, b)
}
func (m *PbExampleGogo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbExampleGogo.Marshal(b, m, deterministic)
}
func (m *PbExampleGogo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbExampleGogo.Merge(m, src)
}
func (m *PbExampleGogo) XXX_Size() int {
	return xxx_messageInfo_PbExampleGogo.Size(m)
}
func (m *PbExampleGogo) XXX_DiscardUnknown() {
	xxx_messageInfo_PbExampleGogo.DiscardUnknown(m)
}

var xxx_messageInfo_PbExampleGogo proto.InternalMessageInfo

func (m *PbExampleGogo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PbExampleGogo) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*PbExampleGogo)(nil), "binary.PbExampleGogo")
}

func init() { proto.RegisterFile("internal/pb/pb_example_gogo.proto", fileDescriptor_5df87a36eeb4579b) }

var fileDescriptor_5df87a36eeb4579b = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcc, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x48, 0xd2, 0x2f, 0x48, 0x8a, 0x4f, 0xad, 0x48, 0xcc, 0x2d,
	0xc8, 0x49, 0x8d, 0x4f, 0xcf, 0x4f, 0xcf, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b,
	0xca, 0xcc, 0x4b, 0x2c, 0xaa, 0x54, 0x32, 0xe5, 0xe2, 0x0d, 0x48, 0x72, 0x85, 0xc8, 0xbb, 0xe7,
	0xa7, 0xe7, 0x0b, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31,
	0x79, 0xba, 0x08, 0x89, 0x70, 0xb1, 0x86, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x81, 0x85, 0x20,
	0x1c, 0x27, 0xde, 0x28, 0x6e, 0x24, 0x3b, 0x92, 0xd8, 0xc0, 0x86, 0x1a, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x16, 0xef, 0x61, 0x04, 0x79, 0x00, 0x00, 0x00,
}
